### ISSUE TITLE
Create automatic tests with github actions and add issues

### ISSUE THREAD

**Issue by yungyuc** [chris901003/PoissonNet#3]
You planned for [basic testing in CI pipeline](https://github.com/yungyuc/nsdhw_24au/blob/f80b9d4b7d7c522934b9f68e650184af4e3c9b7c/project/chris901003/README.rst?plain=1#L126) but there is not GitHub Actions set up yet.  Could you please update where you are for testing?

I wonder if you can create issues for the work items you added in the proposal?

**Comment by yungyuc** [comment]
Any update?

**Comment by chris901003** [comment]
I've been quite busy lately, but I'll catch up on the progress later.
